version: "3.9"

services:
  db:
    image: postgres:17
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-net

  backend:
    build: ./backend
    container_name: weather-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - "4000"
    networks:
      - weather-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - weather-net

volumes:
  pgdata:

networks:
  weather-net:
    driver: bridge