version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - ./db.env   # <-- move DB creds into a separate env file
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-net

  backend:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/weather-backend:latest
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "4000:4000"   # so ECS/EC2 can expose it
    networks:
      - weather-net

  frontend:
    image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/weather-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - weather-net

volumes:
  pgdata:

networks:
  weather-net:
    driver: bridge
